### ISSUE TITLE
Provide admin access to Prime project maintainers

### ISSUE THREAD

**Issue by rbergen** [PlummersSoftwareLLC/OCaml-docker#1]
I suggest we provide the maintainers of the Prime project with admin access to all supporting Docker image repos. I've created a "Prime project maintainers" team that I have granted admin access to all Docker repos that I have created/migrated in this org account.

**Comment by marghidanu** [comment]
Perfect!

**Comment by rbergen** [comment]
Good! The only thing is that you're now the only admin of this repo because you've created it. That means you have to grant us (i.e. the team) admin access :) 
(Actually, Dave could do it to because he is org owner, but I don't think we should bother him with this.)

**Comment by marghidanu** [comment]
Is there a way to configure this at the organization level so we don't have to deal with this option, manually in the future?

**Comment by rbergen** [comment]
There is. @davepl would then have to set "admin" as the base access level within the organization. As this account is the org account for his business, and it may at some point contain repos that are not ours to manage, I do understand he chose not to do that.

**Comment by marghidanu** [comment]
Access granted I will close this. Let's try to get this option sorted out in the future so we can have automatic access! Thanks for pointing that out, I was completely unaware of this.
